### ISSUE TITLE
Mouse over action disabled

### ISSUE THREAD

**Issue by radiodup** [Leleat/AltTab-Mod#1]
Not a bug, but a feature request. 
Allow to disable mouseover action, which really interrupts the workflow. 
Allow to clic on a desired app, but do not change alt tab order.

There is a request on gnome forums, but hasn't been taken.

Feel free to eliminate this issue if it is unrelated.

**Comment by Leleat** [comment]
>  Allow to disable mouseover action, which really interrupts the workflow.

Sorry, but I don't really understand this... Do you mean that, if you click a window in the overview, that the altTab order shouldn't be changed?

**Comment by radiodup** [comment]
If you are alt-tabbing, move the mouse accidentally, and it is hovering any place of the alt-tab , the selection changes.

It happens especially if you are using a notebook with touchpad. 

I understand that is unrelated to the extension, but may be you can hack it somehow.

**Comment by Leleat** [comment]
Ah, okay, now I understand.

Sure, I'll look into it. If it's easy to implement, I am gonna add it as an option to the extension's prefs window (but disabled by default).

**Comment by Leleat** [comment]
Alright, current `master` includes this feature now. I've also uploaded the new version to EGO. Once it's reviewed, you should get an update notification (so probably within the next few days). Note that I've dropped support for GNOME 3.38 and below. So you will only get the new version, if you are on GNOME 40+.
