### ISSUE TITLE
Remove delay not working

### ISSUE THREAD

**Issue by rogama25** [Leleat/AltTab-Mod#14]
The "remove popup delay" is not working for me, neither on Alt Tab nor Super Tab.
Using Ubuntu 24.04 with GNOME 46 on Wayland, extension version is 19

**Comment by Leleat** [comment]
I can't reproduce this (neither on a  Fedora machine nor an Ubuntu VM). AFAIA, there have been no changes on GNOME Shell's side that would really affect this extension in a while. So I only see possible 2 issues:

1. If you are a new user of this extension, are you sure you know what the "Popup Delay" is?
2. Another extension is interferring with this extension by overriding the same method. To test this out: Disable all extensions, __log out and back in__, and re-enable only `Alttab-Mod`. Then test it again.

**Comment by rogama25** [comment]
Okay, it seems to have been related to another extension that I had enabled on the same session. After messing with the other extensions and restarting the gnome session, the problem was no longer there
