### ISSUE TITLE
Remove/extend "Include apps from the current workspace only"

### ISSUE THREAD

**Issue by xalt7x** [Leleat/AltTab-Mod#6]
First of all thanks for resolving my request #5 !  
Unfortunately with the commit  "[Apply features to Window Switcher as well ](https://github.com/Leleat/AltTab-Mod/commit/3ca6330f5d286c927ae398c609486c7d5f342f9f)" this extension now limits isolation feature comparing to vanilla GNOME.

With original GNOME I can use "Super"+"Tab" for "Applications Switching" on all workspaces

`gsettings get org.gnome.shell.app-switcher current-workspace-only`
> false  

and "Alt"+"Tab" for "Windows Switching" on a current workspace only

`gsettings get org.gnome.shell.window-switcher current-workspace-only`
> true

Currently "Alt+Tab mod" overrides both of those settings with a single value.  

I'm not entirely sure whether this "isolation" option is needed for extension. Nowadays "app-switcher" isolation could be set not only with dconf keys but also with the native "Settings" app ("Multitasking" > Application Switching")

**Comment by Leleat** [comment]
Just added separate settings for the window switcher because that is easier since I only need to add some code rather than change existing code and worry about compatibility 🤷‍♂️
